### ISSUE TITLE
Create a build and push action

### ISSUE THREAD

**Issue by RammusXu** [swaglive/actions#4]
## Proposal
Need more reusable action instead of copying same scripts into every repo. like: 
- https://github.com/swaglive/slack-proxy/pull/15
- https://github.com/swaglive/docker-github-actions-runner/pull/3

## Usage
workflow:
```
steps: 
- uses: actions/checkout@v1
- uses: swaglive/actions/docker-release@v1
  with:
    GHR_TOKEN: ${{ secrets.GHR_TOKEN }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    DOCKERHUB_REPOSITORY: swaglive
    DOCKER_IMAGE_NAME: echo-server
    DOCKER_IMAGE_TAG: ${{ github.ref }} or ${{ steps.set-env.outputs.tag }}
    DOCKER_CACHE: true
    DOCKER_WORKDIR: docker
```
required:
- DOCKER_IMAGE_NAME
- DOCKER_IMAGE_TAG

setting -> secrets:
- GHR_TOKEN: `username`:`access_token`
- DOCKERHUB_TOKEN: `username`:`access_token`

## Design
entrypoint.sh
```
GH_REGISTRY=docker.pkg.github.com
DOCKER_WORKDIR=${INPUT_DOCKER_WORKDIR:-.}
if INPUT_DOCKER_CACHE:
  DOCKER_BUILD_OPT="--cache-from $GH_REGISTRY/$GITHUB_REPOSITORY/$INPUT_DOCKER_IMAGE_NAME:$INPUT_DOCKER_IMAGE_TAG"
if INPUT_GHR_TOKEN:
  echo ${INPUT_GHR_TOKEN%%:*} | docker login -u ${INPUT_GHR_TOKEN##*:} --password-stdin $GH_REGISTRY
  DOCKER_BUILD_OPT="$DOCKER_BUILD_OPT -t $GH_REGISTRY/$GITHUB_REPOSITORY/$INPUT_DOCKER_IMAGE_NAME:$INPUT_DOCKER_IMAGE_TAG"
if INPUT_DOCKERHUB_TOKEN:
  echo ${INPUT_DOCKERHUB_TOKEN%%:*} | docker login -u ${INPUT_DOCKERHUB_TOKEN##*:} --password-stdin
  DOCKER_BUILD_OPT="$DOCKER_BUILD_OPT -t $INPUT_DOCKERHUB_REPOSITORY/$DOCKER_IMAGE_NAME:$INPUT_DOCKER_IMAGE_TAG"

test $(echo "$DOCKER_BUILD_OPT" | grep -q -e '-t') && exit 0

docker build $DOCKER_BUILD_OPT $DOCKER_WORKDIR
parallel docker push ::: ${DOCKER_BUILD_OPT//-t/}
```
