### ISSUE TITLE
kubectl - watch rollout status

### ISSUE THREAD

**Issue by RammusXu** [swaglive/actions#7]
## Snippet
```bash
if[ $INPUT_WATCH ]; then
  kubectl rollout status deployment/bot  --namespace=ops --context xxx --timeout=60s
fi
```

## Design
```yaml
    - name: Deploy swaglive-dev
      uses: swaglive/actions/kubectl@f9e1385
      with: 
        context: gke_swag_asia-east1_edge-tw:ops:ops
        args: kubectl apply -k templates/web/swaglive-dev
        watch: deployment/bot     # optional
        namespace: ops           #default: ops
        watch-timeout: 100s     #default: 60s
```
