### ISSUE TITLE
flexible-env - set env depend on push/pull_request/tag

### ISSUE THREAD

**Issue by RammusXu** [swaglive/actions#8]
## Design

```
- use: swaglive/actions/flexible-env
- use: echo ${{ env.FLEXIBLE_GIT_SHA }}
- use: echo ${{ env.FLEXIBLE_GIT_REF }}
```

## Snippets
```
        echo ::set-env name=GIT_SHA::$(git rev-parse --short=10 HEAD)
        echo ::set-env name=GIT_REF::"$(sed 's|[^A-Za-z0-9]|-|g' <<< ${GITHUB_REF#refs/heads/})"
```

```

  pull_sha: 
    description: 'Commit SHA'
    default: "${{ github.event.pull_request.head.sha}}"
    required: false
  push_sha: 
    description: 'Commit SHA'
    required: false
    default: "${{ github.sha }}"
```

```
if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
    COMMIT_SHA=$INPUT_PULL_SHA
else
    COMMIT_SHA=$INPUT_PUSH_SHA
```

ref: https://rammusxu.github.io/toolkit/snippets/github-action/#customize-docker-action
